`text.cpp`: fix missing declaration of `std::rotl`
In C++23 mode, clang libc++ fails to build `text.cpp` with the error:
```
similar/main/text.cpp:60:26: error: no member named 'rotl' in namespace 'std'
   60 |     const uint8_t c2 = std::rotl(c, 1) ^ BITMAP_TBL_XOR;
      |                             ^~~~
similar/main/text.cpp:61:15: error: no member named 'rotl' in namespace 'std'
   61 |     return {std::rotl(c2, 1)};
      |                  ^~~~
```

Add `#include <bit>` to provide this declaration.  gcc happened to
include the required declaration through other means, and so worked
without this include.

Fixes: d73b27d478de5c010544bd67e20623f3e98c708c ("`SConstruct`: use C++23 when available")